name: Surf-Fork
version: 3.2.10
main: org.surf.Main
authors: [ 254n_m, Leeewith3Es, Dreeam, NaixiNana]
description:  ${project.description}
website: https://github.com/Winds-Studio/Surf
api-version: 1.19
commands:
  surf:
    description: Surf Command.
